/**
 * Vite rewrites asset URLs at build time, so filenames coming from content data
 * cannot be interpolated into a path. Resolving a glob up front gives us a
 * lookup from the plain filename the content declares to the hashed build URL.
 */

const logos = import.meta.glob<string>('@/assets/logo/*.svg', {
  eager: true,
  import: 'default',
  query: '?url',
})

const licences = import.meta.glob<string>('@/assets/licences/*.jpg', {
  eager: true,
  import: 'default',
  query: '?url',
})

const licenceDisplays = import.meta.glob<string>('@/assets/licences/*-display.webp', {
  eager: true,
  import: 'default',
  query: '?url',
})

function lookup(map: Record<string, string>, filename: string, kind: string): string {
  const hit = Object.entries(map).find(([path]) => path.endsWith(`/${filename}`))
  if (!hit) {
    throw new Error(`${kind} asset not found: ${filename}. Known: ${Object.keys(map).join(', ')}`)
  }
  return hit[1]
}

export const logoUrl = (filename: string) => lookup(logos, filename, 'logo')

/** The full 2560px scan. Used as the link target, never as the rendered image. */
export const licenceUrl = (filename: string) => lookup(licences, filename, 'licence')

/**
 * The resized WebP actually shown on the page, roughly 87% smaller than the
 * original. Generated by `npm run images`.
 */
export const licenceDisplayUrl = (filename: string) =>
  lookup(licenceDisplays, filename.replace(/\.jpe?g$/i, '-display.webp'), 'licence display')
